# Generated by Django 4.1.7 on 2023-04-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=150)),
                ('company', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=150)),
                ('salary', models.CharField(max_length=150)),
                ('level', models.CharField(max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='Jobs',
        ),
    ]
